const images = [
  {
    birthday: [
      "./gallery/photosHappy/1.jpg",
      "./gallery/photosHappy/2.jpg",
      "./gallery/photosHappy/4.jpg",
      "./gallery/photosHappy/6.jpg",
      "./gallery/photosHappy/7.jpg",
      "./gallery/photosHappy/8.jpg",
      "./gallery/photosHappy/9.jpg",
      "./gallery/photosHappy/10.jpg",
      "./gallery/photosHappy/13.jpg",
      "./gallery/photosHappy/14.jpg",
      "./gallery/photosHappy/halloween1.jpg",
      "./gallery/photosHappy/halloween2.jpg",
      "./gallery/photosHappy/halloween3.jpg",
      "./gallery/photosHappy/halloween4.jpg",
      "./gallery/photosHappy/halloween5.jpg",
      "./gallery/photosHappy/halloween6.jpg",
      "./gallery/photosHappy/halloween7.jpg",
      "./gallery/photosHappy/halloween8.jpg",
      "./gallery/photosHappy/15.jpg",
      "./gallery/photosHappy/16.jpg",
      "./gallery/photosHappy/18.jpg",
      "./gallery/photosHappy/19.jpg",
      "./gallery/photosHappy/20.jpg",
      "./gallery/photosHappy/21.jpg",
      "./gallery/photosHappy/22.jpg",
      "./gallery/photosHappy/23.jpg",
      "./gallery/photosHappy/24.jpg",
      "./gallery/photosHappy/25.jpg",
      "./gallery/photosHappy/26.jpg",
    ],
    pets: [
      "./gallery/pets/pet1.jpg",
      "./gallery/pets/pet2.jpg",
      "./gallery/pets/pet3.jpg",
      "./gallery/pets/pet4.jpg",
      "./gallery/pets/pet5.jpg",
      "./gallery/pets/pet6.jpg",
      "./gallery/pets/pet7.jpg",
      "./gallery/pets/pet8.jpg",
      "./gallery/pets/pet9.jpg",
      "./gallery/pets/pet10.jpg",
      "./gallery/pets/pet11.jpg",
      "./gallery/pets/pet12.jpg",
      "./gallery/pets/pet13.jpg",
      "./gallery/pets/pet14.jpg",
      "./gallery/pets/pet15.jpg",
      "./gallery/pets/pet16.jpg",
      "./gallery/pets/pet17.jpg",
      "./gallery/pets/pet18.jpg",
      "./gallery/pets/pet19.jpg",
      "./gallery/pets/pet20.jpg",
      "./gallery/pets/pet21.jpg",
      "./gallery/pets/pet22.jpg",
    ],
    cakes: [
      "./gallery/cakes/bolo1.jpg",
      "./gallery/cakes/bolo2.jpg",
      "./gallery/cakes/bolo3.jpg",
      "./gallery/cakes/bolo4.jpg",
      "./gallery/cakes/bolo5.jpg",
      "./gallery/cakes/bolo6.jpg",
      "./gallery/cakes/bolo7.jpg",
      "./gallery/cakes/bolo8.jpg",
      "./gallery/cakes/bolo9.jpg",
      "./gallery/cakes/bolo10.jpg",
      "./gallery/cakes/bolo11.jpg",
      "./gallery/cakes/bolo12.jpg",
      "./gallery/cakes/bolo13.jpg",
      "./gallery/cakes/bolo14.jpg",
      "./gallery/cakes/bolo15.jpg",
      "./gallery/cakes/bolo16.jpg",
      "./gallery/cakes/bolo17.jpg",
    ],
    products: [
      "./gallery/products/product1.jpg",
      "./gallery/products/product2.jpg",
      "./gallery/products/product3.jpg",
      "./gallery/products/product4.jpg",
      "./gallery/products/product5.jpg",
      "./gallery/products/product6.jpg",
      "./gallery/products/product7.jpg",
      "./gallery/products/product8.jpg",
      "./gallery/products/product9.jpg",
      "./gallery/products/product10.jpg",
      "./gallery/products/product11.jpg",
      "./gallery/products/product12.jpg",
      "./gallery/products/product13.jpg",
      "./gallery/products/product14.jpg",
      "./gallery/products/product15.jpg",
      "./gallery/products/product16.jpg",
      "./gallery/products/product17.jpg",
      "./gallery/products/product18.jpg",
      "./gallery/products/product19.jpg",
      "./gallery/products/product20.jpg",
      "./gallery/products/product21.jpg",
      "./gallery/products/product22.jpg",
      "./gallery/products/product23.jpg",
      "./gallery/products/product24.jpg",
      "./gallery/products/product25.jpg",
      "./gallery/products/product26.jpg",
      "./gallery/products/product27.jpg",
      "./gallery/products/product28.jpg",
    ]
  },
];

const searchBirthday = images.map((photos) => photos.birthday);
const searchPets = images.map((photos) => photos.pets);
const searchCakes = images.map((photos) => photos.cakes);
const searchProducts = images.map((photos) => photos.products);

export { searchBirthday, searchPets, searchCakes, searchProducts };
